### ISSUE TITLE
Portable still writes to /AppData/Roaming

### ISSUE THREAD

**Issue by dabugen** [portapps/skype-portable#1]
The portable version still creates these directories (including some files in there) directly on the system it runs on:

C:\Users\ -user- \AppData\Roaming\Microsoft\Skype for Desktop
C:\Users\ -user- \AppData\Roaming\Skype

Being tagged as portable, those directories should not be created on the host system, or should at least be removed once Skype was fully shutdown, but the directories persist in both cases.

**Comment by paradoxicallist** [comment]
Thanks for making Skype 8.x portable.

But I ask for the same issue as @dabugen

**Comment by crazy-max** [comment]
I will investigate on this, thx for your feedback

**Comment by crazy-max** [comment]
Must be solved in the latest release.
For your information, `C:\Users\ -user- \AppData\Roaming\Skype` is hardcoded in `skypert.dll` and it's a temp directory not needed during execution so it will be removed when Skype is closed.
And i have managed to move `C:\Users\ -user- \AppData\Roaming\Microsoft\Skype for Desktop` in the `data` folder.

**Comment by paradoxicallist** [comment]
Thanks. Downloading right now and testing later on tonight.

**Comment by MrX-at-GitHub** [comment]
Hi @crazy-max 

It keeps writing to:
C:\Users\user\Skype\user\current\AppData\Roaming\Skype\logs 
C:\Users\user\Skype\user\current\AppData\Roaming\Skype\SkypeRT

**Comment by dabugen** [comment]
Thanks a lot, will test too!

**Comment by paradoxicallist** [comment]
Thank you, version 8.20.0.9-12 working good here as expected.

**Comment by teamayu** [comment]
Latest version is still writing to appData folder:

AppData/Roaming/Microsoft/Skype for Desktop
AppData/Roaming/Microsoft/Skype for Desktop/SkypeRT/*
AppData/Roaming/Microsoft/Skype for Desktop/CS_skylib/*

But thanks for your hard word Max, you`ve done a great job. Hopefully this Skype issue can be fixed in a future version.

**Comment by crazy-max** [comment]
@teamayu Yes indeed, but those files inside `AppData/Roaming/Microsoft/Skype for Desktop` are hardcoded inside Skype. What we can do is removing this folder on close. Can you open a proper [bug report](https://github.com/portapps/skype-portable/issues/new?template=bug_report.md) about this please ?
