### ISSUE TITLE
problems connecting with microphone on skype 8.54.0.91-73

### ISSUE THREAD

**Issue by felipemm** [portapps/skype-portable#13]
I'm currently using skype 8.54.0.91-73 and I'm having problems connecting to the microphone to do calls. the microphone works fine on microsoft Teams and Skype Web, and even when I launch the Skype.exe under the app/ folder it works just fine, but when I'm using the launcher, I just can't use it. I notice that when I am able to use the microphone, the mic icon appears on windows system tray. My windows 10 is on version 1903, os build 18362.295, and the machine is using Kaspersky Endpoint Security for policy enforcement on the OS.

Appreciate the help.

Thanks,
Felipe

**Comment by felipemm** [comment]
I notice that when using the portable skype launcher, the "last accessed" timestamp under windows settings > privacy > microphone do not get updated. It only updates when accessing the Skype.exe executable directly.

![image](https://user-images.githubusercontent.com/2068687/70542161-02185b00-1b47-11ea-9e6c-58a7cff45413.png)

**Comment by crazy-max** [comment]
@felipemm I cannot reproduce your issue on Skype 8.55.0.135, maybe try to update to the last release. And for the next time please create a proper [bug report](https://github.com/portapps/skype-portable/issues/new?template=bug_report.md).
