### ISSUE TITLE
Skype for Desktop folder

### ISSUE THREAD

**Issue by zwiebus** [portapps/skype-portable#14]
It allways leaves two folders (CS_skylib, SkypeRT) with config files in 
%APPDATA%\Microsoft\Skype for Desktop\.
If the 'Skype for Desktop' folder does not exist, its anew provided.

**Comment by crazy-max** [comment]
@zwiebus You can set `cleanup: true` in the configuration file to remove these folders. See https://portapps.io/app/skype-portable/#configuration

**Comment by zwiebus** [comment]
I set _cleanup: true_ , but every time i start skype it's change to _cleanup: false_

**Comment by crazy-max** [comment]
@zwiebus You have to rename `[appname]-portable.sample.yml` to `[appname]-portable.yml`. The sample file is overwritten at launch. See https://portapps.io/doc/configuration/
