### ISSUE TITLE
again antivirus pesting

### ISSUE THREAD

**Issue by caspertone2003** [portapps/skype-portable#19]
23 engines of virustotal detect the portable exe as a serious troyan
https://www.virustotal.com/gui/file/05a83f18b460f6707034f90527671582aa9dba1cd20a5f3c5daa4e6fe05f711d/detection

points to a very dirty troyan called wacatac...

First notice form MS defender was a shock (I was not sure of the source of the portable), as soon as I verified it was portapps my heartrate descended...

Time again to contact engine runners for clearing portapps reputation?

Thanks again for portapps apps...
CT

**Comment by crazy-max** [comment]
@caspertone2003 You can contact them yourself following this [section in the FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper). I just sent the wrapper to Microsoft and BitDefender. Should take a day or two to be whitelisted. See also portapps/portapps#68 and https://github.com/search?q=org%3Aportapps+antivirus&type=Issues. Thanks for your support.
