### ISSUE TITLE
Skype 8.59.0.77 cant access webcam or microphone

### ISSUE THREAD

**Issue by azcmc** [portapps/skype-portable#26]
### Behaviour
Microphone and webcam are not working

#### Steps to reproduce this issue

1. run the app

#### Expected behaviour

in settings> audio video > input from webcam and microphone is visible
When calling someone other end will hear my voice or see my video 

#### Actual behaviour
In settings> audio video > no input from webcam or Audio
or
When calling someone other end doesn't hear my voice or see my video 

### Configuration

**skype version 8.59.0.77
   both zip and installer

**Operating system: windows 10 enterprise 2016 LTSB
Note: Not an administrator.

![image](https://user-images.githubusercontent.com/17346900/82871992-34cada00-9f54-11ea-811f-c2e9a0e4413a.png)

![image](https://user-images.githubusercontent.com/17346900/82872098-60e65b00-9f54-11ea-8c5f-add0dc6509bf.png)

### Logs

[skype-portable.log](https://github.com/portapps/skype-portable/files/4680530/skype-portable.log)

**Comment by crazy-max** [comment]
Is it working with a standard Skype installation ?
