### ISSUE TITLE
Windows AntiVirues detect Trojan:Win32/Vigorf.A

### ISSUE THREAD

**Issue by Hananel-Hazan** [portapps/skype-portable#27]
### Behaviour
After installing the last version of portable Skype 

#### Steps to reproduce this issue

1. Install portable Skype ver 8.60.0.76
2. Update windows 10 build in antivirus 
3. Run antivirus scan on the directory

### Configuration

**Skype™ portable app made with Portapps.** 
Latest version | 8.60.0.76
Internal release | 81
Last updated | 2020/05/29
Links |  
Maintainer | CrazyMax
Homepage | https://www.skype.com/get-skype
License | Freemium
Changelog | CHANGELOG.md

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 1909

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/3954715/83760122-7dfce700-a642-11ea-8ce5-5329df051103.png)

### Screenshots

![image](https://user-images.githubusercontent.com/3954715/83760069-6b82ad80-a642-11ea-8baa-15f97a8ffe80.png)

**Comment by crazy-max** [comment]
Hi @Hananel-Hazan, this has been discussed [many times](https://github.com/search?q=org%3Aportapps+virus&type=Issues). Please see https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper
