### ISSUE TITLE
Where is "old login", I see Microsoft only..

### ISSUE THREAD

**Issue by Gennady-G** [portapps/skype-portable#3]
Hi!

Subj.

Best regards, 
Gennady

**Comment by tngreene** [comment]
If you were coming from Skype 7.4 like I was, I was surprised to see it ask for a Microsoft account. I put in my Skype name and password anyway and it let me in. I'm not sure if that is what you're referring to as the "old login".

**Comment by crazy-max** [comment]
As @tngreene said

**Comment by Gennady-G** [comment]
@tngreene , thank You much for response! Yes, I mean Skype account as "old login" :)
