### ISSUE TITLE
Keep receiving A JavaScript error on statt

### ISSUE THREAD

**Issue by Elaneor** [portapps/skype-portable#34]
### Behaviour
It's stops in start with a Javascript error
But starts 3 skype Processes
#### Steps to reproduce this issue

1. Tried to update my previous version (installed upon existing files)
2. Deleted files in directory and installed again
3. Tried running As Administrator

#### Expected behaviour

> IT should start as usual
### Behaviour
It's stops in start with a Javascript error
But starts 3 skype Processes
#### Steps to reproduce this issue

1. Tried to update my previous version (installed upon existing files)
2. Deleted files in directory and installed again
3. Tried running As Administrator

#### Expected behaviour

> IT should start as usual

#### Actual behaviour

It's stops at start with a Javascript error
But starts 3 skype Processes instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
![2020-09-23_10-51-22](https://user-images.githubusercontent.com/29975146/93983278-05ee3480-fd8b-11ea-858a-c7d6d652ff2a.png)

#### Actual behaviour

> 

### Configuration

*** : 8.64.0.80-85

**Operating system (Windows 10 Enterpise 64 bit)

64 bits)** :

**Winver screenshot** :

> [vinver](https://user-images.githubusercontent.com/29975146/93983465-42219500-fd8b-11ea-8eec-d27c4306337e.png)

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

[skype-portable.log](https://github.com/portapps/skype-portable/files/5266508/skype-portable.log)

**Comment by crazy-max** [comment]
@Elaneor Thanks for your report but I cannot reproduce your issue:

![image](https://user-images.githubusercontent.com/1951866/94596298-79a4ab80-027b-11eb-9747-9be923f2105f.png)

Can you try in another folder and also check with a previous version (8.63.0.76-84)?

**Comment by Elaneor** [comment]
Technically
i resolved this problem when I just deinstalled it and then used the file archive (not the installer).

**Comment by crazy-max** [comment]
@Elaneor Can you send me the link of the setup you have used before?

**Comment by Elaneor** [comment]
Last one I tried skype-portable-win32-8.64.0.80-85-setup.exe
from here https://portapps.io/download/skype-portable-win32-8.64.0.80-85-setup.exe/
The .7z archive from there worked pretty fine 
Thank you for your concern!~

**Comment by crazy-max** [comment]
@Elaneor That's strange the portable setup and 7z archive literally contain the same files. Where do you install/extract the app with portable setup?
