### ISSUE TITLE
Is This a False Alarm In Skype (Trojan)

### ISSUE THREAD

**Issue by taskmann** [portapps/skype-portable#4]
Hello Developer,

Thanks for the great work!

Each time I unzip portable skype Windows Defender (Windows 10) detect this trojan

Trojan:Win32/Zpevdo.A

Should I be concerned about this?

**Comment by crazy-max** [comment]
Hi @taskmann, this is a [false positive](https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker). I have submitted the exe to Microsoft for analysis and automatic scanning has given a clean result (as expected) on their website :

![image](https://user-images.githubusercontent.com/1951866/43200168-e1bd7c3c-9014-11e8-8dc5-4705a1b09664.png)

Just waiting for them to confirm and hopefully it shout be sorted in the next definition update of Windows Defender.

**Comment by taskmann** [comment]
Thanks for taking the time to look into this.  

I do appreciate how quickly and efficiently you have addressed this concern.

I am at peace using this application.

Again, thanks for the great work!

Kind regards.

**Comment by MrMorfey** [comment]
but mb in next releases u will fix it?

**Comment by crazy-max** [comment]
@MrMorfey Depends on signature mitigation of Antivirus providers but the latest release seems ok :)
