### ISSUE TITLE
Jitsi Meet as an alternative?

### ISSUE THREAD

**Issue by hoasis2** [portapps/skype-portable#40]
Sorry for off topic, @crazy-max. 
[Jitsi Meet](https://github.com/jitsi/jitsi-meet-electron) Electron Client is a good open source alternative.

Do you have plans to ever build an Jitsi Meet portable application?

Thanks for all the other apps.
Cheers!

**Comment by crazy-max** [comment]
Hi @hoasis2,

See portapps/portapps#120.
About app requests see also https://portapps.io/doc/request-app/
