### ISSUE TITLE
Detected Trojan:Win32/Wacatac.D5!ml in skype-portable-win32-8.67.0.99-88-setup.exe

### ISSUE THREAD

**Issue by paololeo** [portapps/skype-portable#43]
### Behaviour
Hallo 

I dowloaded the file skype-portable-win32-8.67.0.99-88-setup.exe
from https://portapps.io/app/skype-portable/#download
and my Win10 detected a trojan inside 
with the following signature

Trojan:Win32/Wacatac.D5!ml

Operating system : Windows 10 Pro 64 bits)
with Windows defender

How it is possible ?

thank you in advance

Paolo

**Comment by crazy-max** [comment]
@paololeo https://github.com/portapps/skype-portable/issues/27#issuecomment-638898886
