### ISSUE TITLE
Skype-Portable on USB-Stick - Windows Defender Issue

### ISSUE THREAD

**Issue by Sunny3885** [portapps/skype-portable#47]
### Behaviour
I'm using Skype-Portable for years without Issues, but at my **Work**notebook I've got the following Issue.
Other portable Apps I can use normally.

When I start Skype-Portable, the Windows-Defender on Windows 10 (20H2 19042.867) blocks the Application with the note "Blocked not trusted or not signed Processes running on USB".
While Googling I found the "[Block untrusted and unsigned processes that run from USB](https://docs.microsoft.com/de-de/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-untrusted-and-unsigned-processes-that-run-from-usb)".

Is there anything I can do or is something possible to change something in Code?

### Screenshots
![image](https://user-images.githubusercontent.com/82082021/113826762-d4ffab00-9782-11eb-92a2-9aea9078dd52.png)

Thanks a lot and best regards
Alex

**Comment by crazy-max** [comment]
@Sunny3885 Skype portable is not signed that's why. See https://github.com/portapps/portapps/issues/68
