### ISSUE TITLE
Error related to JSON

### ISSUE THREAD

**Issue by Anx2k** [portapps/skype-portable#53]
### Behaviour

Running the latest version (8.73.0.92) on Windows 7 Pro, when launching the app it shows the following error:

"Cannot unmarshal portapp-prev: unexpected end of JSON input"

#### Steps to reproduce this issue

1. Create an empty file "portapp-prev.json"
2. Launch app

#### Expected behaviour

Program should launch

#### Actual behaviour

It reports error and exits (so you can't actually run Skype).

I didn't originally create this file - so something in the app must have done it, and then I'm assuming it failed to correctly write the file, instead creating an empty file.  If you delete this file, then Skype launches correctly again, but thought it was worth pointing out as it's easily reproducible and should be easy to fix - I just don't know how common this issue is (as it's the first time I've ever encountered it).

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/217#issuecomment-903357074
