### ISSUE TITLE
App does not start and shows huge error message that causes crash

### ISSUE THREAD

**Issue by starsoccer** [portapps/skype-portable#56]
#### Steps to reproduce this issue

1. Start skyp-portable app

#### Expected behaviour

> App should start

#### Actual behaviour

> Nothing happens for a few seconds to minute then a big error popup appears.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : Latest Version

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 64bit

**Winver screenshot** : 20H2 19042.1466

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[skype-portable.log](https://github.com/portapps/skype-portable/files/7964835/skype-portable.log)

**Comment by cybermcm** [comment]
same here (windows 10, latest updates)

**Comment by crazy-max** [comment]
was able to reproduce, keep you in touch with a fix.

**Comment by zwiebus** [comment]
same with windows 7 latest updates

**Comment by Robcsa78** [comment]
Same error in Windows10

**Comment by starsoccer** [comment]
Any word on a fix?

**Comment by crazy-max** [comment]
Ok that's an issue with GitHub Windows Runners messing up the encoding of files.

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://portapps.io/app/skype-portable/#download

**Comment by cybermcm** [comment]
can confirm, version 8.82.0.403-92 is working again, thanks!

**Comment by starsoccer** [comment]
confirm fixed too
