### ISSUE TITLE
DATA folder absent after fresh installation

### ISSUE THREAD

**Issue by andzi** [portapps/skype-portable#7]
### Behaviour
After fresh installation there is no folder `data`, so it's impossible to move files as it is suggested in _Installation Help_

#### Steps to reproduce this issue

1. Download file from github
2. Install to desired PortableApps directory (for example ..portapps/skype-portable/)
3. Unable to find `data` folder

#### Expected behaviour
On order to follow this instruction:

> If you have already installed Skype from the original setup, do the same thing as a fresh installation and move files :    %APPDATA%\Microsoft\Skype for Desktop\* to data

Empty folder `data` should be created (by default) on installation (actually, term _installation_ is misleading, this is _unpacking_)

> ..portapps/skype-portable/data/

#### Actual behaviour

`data` folder is absent.

### Configuration

**App release / arch** : skype-portable-win32-8.36.0.52-28-setup.exe

**Operating system** :  Windows 10 HE 64-bits

**Winver screenshot** :

![winver screenshot_1547945055](https://user-images.githubusercontent.com/1347721/51433867-74492e00-1c5d-11e9-92f3-4f96c600beae.png)

### Screenshots

![screenshot_1547945947](https://user-images.githubusercontent.com/1347721/51433965-179b4280-1c60-11e9-97f9-efb38e37bde5.png)

### Logs

Join the log file `skype-portable.log` to this issue.

**Comment by crazy-max** [comment]
Thanks for this concise report. The `data` folder is created at first launch, not installation. This behaviour is the same for the archive (.7z) package. So you have just to create a new folder `data` and move files. If you don't know how to create a new folder on Windows, [follow this thread](https://www.officearticles.com/misc/create_a_folder_on_your_desktop_in_microsoft_windows.htm).

**Comment by andzi** [comment]
The problem is not about "how to create folder", but folder must be present to move data into it. So 2 options exists:

- help text should be fixed or 
- installer behaviour.
